# Generated by Django 3.2 on 2022-08-17 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
