# Generated by Django 3.2 on 2022-07-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=' ', upload_to='Category/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
