# Generated by Django 3.2 on 2022-07-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=b'I01\n', null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
